name: Casa Martelli
weather: weather.home
recap: !include recap.yaml
rooms: !include_dir_list ./rooms
most_used:
  - entity_id: group.areas_soggiorno
    name: Soggiorno
  - entity_id: light.corridoio_notturna
    name: Corridoio
  - entity_id: light.cameretta_scrivania
    name: Scrivania
  - entity_id: light.cortile_frontale
    name: Cortile
  - entity_id: lock.cortile_pedonale
    name: Pedonale
scenes:
  - entity_id: scene.cena_fuori
  - entity_id: scene.tutto_spento
