#Â lovelace_gen

- title: Impostazioni
  icon: mdi:settings
  path: settings
  cards:
    - !include
      - ../includes/header.yaml
      - title: "Impostazioni"
    - type: vertical-stack
      cards:
        - !include
          - ../includes/section.yaml
          - title: "Internet"
        - type: horizontal-stack
          cards:

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.speedtest_upload
                - color: purple
                - name: Upload

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.speedtest_download
                - color: red
                - name: Download

    - type: vertical-stack
      cards:
        - !include
          - ../includes/section.yaml
          - title: "AdGuard"

        - type: entities
          entities:
            - sensor.adguard_dns_queries_blocked
            - switch.adguard_filtering

    - type: vertical-stack
      cards:

        - !include
          - ../includes/section.yaml
          - title: "Stampante"
        - type: custom:auto-entities
          card:
            type: glance
          filter:
            include:
              - entity_id: sensor.corridoio_stampante_*_ink
        - type: entities
          entities:
            - sensor.corridoio_stampante_status

    - type: vertical-stack
      cards:

        - !include
          - ../includes/section.yaml
          - title: "Altro"
        - type: entities
          entities:
            - input_select.sistema_stato_del_giorno
            - binary_sensor.casa_presenza_acqua
