---
name: Home Assistant CI

on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: Pre Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.3.3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pre-commit
          pip list
          pre-commit --version
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure

  home_assistant_stable:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2.3.3
      - name: Copy stub files into configuration folder
        run: |
          cp .stubs/secrets.yaml homeassistant/secrets.yaml
          cp .stubs/google_token.json homeassistant/google_token.json
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config ./homeassistant/ --script check_config --info all
  home_assistant_beta:
      needs: pre-commit
      runs-on: ubuntu-latest
      steps:
        - name: Getting your configuration from GitHub
          uses: actions/checkout@v2.3.3
        - name: Copy stub files into configuration folder
          run: |
            cp .stubs/secrets.yaml homeassistant/secrets.yaml
            cp .stubs/google_token.json homeassistant/google_token.json
        - name: Home Assistant Version
          uses: "docker://homeassistant/home-assistant:beta"
          with:
            args: |
              python -m homeassistant --version
        - name: Home Assistant Check
          uses: "docker://homeassistant/home-assistant:beta"
          with:
            args: python -m homeassistant --config ./homeassistant/ --script check_config --info all

  esphome:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2.3.3
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.3.3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy stub files into configuration folder
        run: cp -R ./.stubs/esphome_secrets.yaml ./homeassistant/esphome/secrets.yaml
      - name: Run esphome on all files
        run: |
          for file in $(find ./homeassistant/esphome -type f -name "*.yaml" -not -name "secrets.yaml" -not -name "*_common.yaml"); do esphome "${file}" config; done
